DATATSETS: 
  TRAIN: ("damage_train")
  TEST: ("damage_val")
MODEL: 
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1 
SOLVER:
  IMS_PER_BATCH: 1 
  BASE_LR: 0.00025
  MAX_ITER: 300 
  STEPS: []
DATALOADER: 
  NUM_WORKERS: 2 
